<?php

namespace RabbitLoader\Laravel;

use Closure;
use RabbitLoader\SDK as SDK;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\URL;

class Process
{
    private static $isActive;
    private $rlSDK = null;

    function __construct()
    {
        $licenseKey = config('rabbitloader.licenseKey', '');
        $cacheDir = config('rabbitloader.cacheDir', '');
        $skipPaths = config('rabbitloader.skipPaths', []);
        $skipCookies = config('rabbitloader.skipCookies', []);
        $ignoreParams = config('rabbitloader.ignoreParams', []);
        $meMode = config('rabbitloader.meMode', false);

        $this->rlSDK = new SDK\RabbitLoader($licenseKey, $cacheDir);

        $this->rlSDK->skipForPaths($skipPaths);

        $this->rlSDK->skipForCookies($skipCookies);

        $this->rlSDK->ignoreParams($ignoreParams);

        if ($meMode) {
            $this->rlSDK->setMeMode();
        }

        $this->rlSDK->setPlatform([
            'plugin_cms' => 'laravel',
            'plugin_v' => '1.3.0',
            'cms_v' => App::version()
        ]);

        $this->rlSDK->setDebug(config('rabbitloader.debugMode', false));

        $this->rlSDK->registerPurgeCallback(function ($url) {
            //cache invalidated/regenerated by RabbitLoader for $url
            //you may want to purge your hosting cache, or do something with it
        });
    }

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \Closure $next
     * @return \Illuminate\Http\Response $response
     */
    public function handle($request, Closure $next)
    {
        // Remove the specified query parameters
        $paramsToRemove = ['rl-no-optimization', 'norl', 'rl-warmup', 'rltest', 'rl-rand', 'rl-only-after'];
        $query = $request->query();
        foreach ($paramsToRemove as $param) {
            if (array_key_exists($param, $query)) {
                unset($query[$param]);
            }
        }
        // Update the request query parameters
        $request->query->replace($query);

        //call next middleware
        $response = $next($request);

        if (!$this->isActive()) {
            return $response;
        }

        $html = $response->getContent();
        $this->setCanonical($html);

        $this->rlSDK->process();

        return $response->setContent($html);
    }

    /**
     * isActive - checks if the RL package is active
     * @return bool
     */
    protected function isActive()
    {
        if (!is_null(static::$isActive)) {
            return static::$isActive;
        }

        static::$isActive = (bool) config('rabbitloader.active', true);

        return static::$isActive;
    }

    /**
     * setCanonical - adds a meta tag with canonical URL
     * @return bool
     */
    private function setCanonical(&$html)
    {
        $headElements = '';
        $canURL = URL::current();
        if (!empty($canURL)) {
            $headElements .= "<meta name='rl:url' content='$canURL'>";
        }

        $headElements .= "<script data-rlskip='1'>window.setTimeout(function(){if(rlPageData&&rlPageData.rlCached){var e=`querySelectorAll`;let t=document[e](`input[type='hidden'][name='_token']`),n=document[e](`meta[name='csrf-token']`);(0!=t.length||0!=n.length)&&fetch(`/rl-csrf-token`).then(e=>e.json()).then(e=>{e.csrf_token&&(t.forEach(t=>{t.value=e.csrf_token}),n.forEach(t=>{t.setAttribute(`content`,e.csrf_token)}))})}},1e3);</script>";

        $html = str_ireplace('</head>', $headElements . '</head>', $html, $replaced);
    }
}
